### ISSUE TITLE
can you make the introductory version of Lean4, i cant find one. 

### ISSUE THREAD

**Issue by mrizklh** [arthurpaulino/lean4-metaprogramming-book#54]
hi there i believe we will note survive climate change, mathematics is the pinnacle of human ingenuity. i am from indonesia. i think i can help popularize Lean Therorem Prover 4 in indonesia.

**Comment by arthurpaulino** [comment]
@mrizklh I didn't understand it. What do you mean? This is not an introductory book

**Comment by arthurpaulino** [comment]
I'll close this for now. Let me know if you need more help.
