### ISSUE TITLE
`md` parameter of `whnf'` is unused

### ISSUE THREAD

**Issue by dwrensha** [arthurpaulino/lean4-metaprogramming-book#55]
In the `MetaM` chapter, `whnf'` has an unused `md` parameter:

https://github.com/arthurpaulino/lean4-metaprogramming-book/blob/b7762483d16577eb2f25d6a57942f76054acb578/lean/main/metam.lean#L621-L625

It looks to me like this should be removed.

Lower down, the transparency mode is controlled via `withTransparency`:

https://github.com/arthurpaulino/lean4-metaprogramming-book/blob/b7762483d16577eb2f25d6a57942f76054acb578/lean/main/metam.lean#L647

cc @JLimperg, who added this section as part of #34.

**Comment by JLimperg** [comment]
Indeed this was left over from an earlier version of the text. Thank you for the fix!
