### ISSUE TITLE
Introduction chapter: Getting an error on assertTypeCmd in Lean4

### ISSUE THREAD

**Issue by lakesare** [arthurpaulino/lean4-metaprogramming-book#75]
I'm getting the following error in the [Introduction#Building a command](https://github.com/arthurpaulino/lean4-metaprogramming-book/blob/master/md/main/intro.md#building-a-command) example.   
My Lean version is "leanprover/lean4:nightly-2022-10-09".
Does this look familiar?

<img width="911" alt="image" src="https://user-images.githubusercontent.com/7578559/195123429-757aaf9e-bd28-47f2-a97f-cbb1c8a6caad.png">

**Comment by arthurpaulino** [comment]
Oh, the API must have changed. What happens if you don't pass the `` `assertTypeCmd`` argument?

**Comment by lakesare** [comment]
It goes like this:

<img width="914" alt="image" src="https://user-images.githubusercontent.com/7578559/195128399-0594bfe0-e688-4339-851c-8be304f3ded5.png">

**Comment by arthurpaulino** [comment]
@lakesare I've bumped the toolchain and fixed that issue: https://github.com/arthurpaulino/lean4-metaprogramming-book/commit/ec355bba83e3d65db57952f13abc23a32cafd009

Make sure to check the indentation levels of your code because the `try ...` needs to be deeper than `liftTermElabM`

**Comment by lakesare** [comment]
That worked! Thanks for the note about the nesting level, that was also important.
